export const botsControlStabs_1 = [
  {
    id: 'botRule1',
    createdAt: '2025-10-15T10:30:00.000Z',
    actionCount: 5,
    errorCount: 1,
    lastActionTimeStart: '2025-11-05T12:45:30.123Z',
    status: 'active',
    isSendData: true,
    running: true,
  },
  {
    id: 'botRule2',
    createdAt: '2025-10-15T09:15:00.000Z',
    actionCount: 12,
    errorCount: 0,
    lastActionTimeStart: '2025-10-15T12:40:15.456Z',
    status: 'pending',
    isSendData: false,
    running: true,
  },
  {
    id: 'botRule3',
    createdAt: '2025-10-15T11:20:00.000Z',
    actionCount: 8,
    errorCount: 3,
    lastActionTimeStart: '2025-10-15T12:35:45.789Z',
    status: 'error',
    isSendData: true,
    running: false,
  }
];
//
// export const botsControlStabs_1 = [
//   {
//     id: 'req-001',
//     gate: 'Gate-A',
//     maxTimeRequest: 2500,
//     TimeRequest: 1800,
//     status: 'active',
//     isSendData: true,
//     isStart: true,
//   },
//   {
//     id: 'req-002',
//     gate: 'Gate-B',
//     maxTimeRequest: 3000,
//     TimeRequest: 3200,
//     status: 'pending',
//     isSendData: false,
//     isStart: true,
//   },
//   {
//     id: 'req-003',
//     gate: 'Gate-C',
//     maxTimeRequest: 2000,
//     TimeRequest: 2400,
//     status: 'error',
//     isSendData: true,
//     isStart: false,
//   },
//   {
//     id: 'req-004',
//     gate: 'Gate-D',
//     maxTimeRequest: 4000,
//     TimeRequest: 3700,
//     status: 'closed',
//     isSendData: false,
//     isStart: false,
//   },
//   {
//     id: 'req-005',
//     gate: 'Gate-E',
//     maxTimeRequest: 1500,
//     TimeRequest: 1400,
//     status: 'active',
//     isSendData: true,
//     isStart: true,
//   },
// ];
